version: "3.9"

services:
  # Serviço do Apache + PHP
  app:
    image: php:8.2-apache
    container_name: php-app
    volumes:
      - ./public:/var/www/html # onde ficam os arquivos acessíveis
      - ./app:/var/www/app # código do app
      - ./src:/var/www/src # código fonte extra
    ports:
      - "80:80" # acessa em http://localhost
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=poqmon_db
    working_dir: /var/www/html
    command: >
      bash -c "docker-php-ext-install mysqli && apache2-foreground"

  # Serviço do MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poqmon_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql # dados persistentes

  # phpMyAdmin opcional
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80" # acessa em http://localhost:8080
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
